### ISSUE TITLE
Option Format

### ISSUE THREAD

**Issue by sajpsensei** [zaki-yama/copy-title-and-url-as-markdown#20]
Version 1.7
i can't change format option
example: ${title}\n${url} or ${title}\t${url}
but only format [${title}] (${url})
You can add option format 2 cell for excel ?
Cell1      Cell2
${title}]  (${url})

I using Edge. Thank you

**Comment by zaki-yama** [comment]
@sajpsensei 
Thank you for your feedback.
I'm terribly sorry that currently the custom format option doesn't seem to work.
I've already published the fixed version 1.8.0, so please wait for a little.

But even if it's fixed, I found that it still doesn't support tab (`\t`) format, so I deal with it in #22 .

Also,

> You can add option format 2 cell for excel ?

This would be supported in #14 .

**Comment by zaki-yama** [comment]
Closed because v1.8.0 was released
