### ISSUE TITLE
この拡張機能は、Chrome 拡張機能のベスト プラクティスに沿わないため、まもなくサポートされなくなる可能性があります。

### ISSUE THREAD

**Issue by t-ueno-ruby** [zaki-yama/copy-title-and-url-as-markdown#344]
I find it extremely useful and helpful.
The other day, the following message appeared.
I've tried other extensions of the same type, but I haven't found any other useful extensions that display a popup to let me know that something has been copied.
I'd appreciate it if you could address this issue.
Thank you in advance.

[拡張機能をインストールして管理する - Chrome ウェブストア ヘルプ](https://support.google.com/chrome_webstore/answer/2664769)

![08-29_8_35_17](https://github.com/user-attachments/assets/af573774-f05e-4ef3-9b9d-002448979676)

**Comment by zaki-yama** [comment]
@t-ueno-ruby 
I really appreciate your report.
The reason for the message appearing could possibly be that the extension is not yet compatible with Manifest v3.
I recently completed the transition to Manifest v3 (#218), but I forgot to release the update.

I'll release the newer version later. Thank you.

**Comment by zaki-yama** [comment]
@t-ueno-ruby 
I released the latest version that supports Manifest v3.
Thanks!
