### ISSUE TITLE
how to change shortcut?

### ISSUE THREAD

**Issue by shyr** [zaki-yama/copy-title-and-url-as-markdown#36]
I want to change shortcut, but cannot find in options.
How can I change shortcut?

**Comment by zaki-yama** [comment]
@shyr 
Thanks for your question.
Please open `chrome://extensions/shortcuts`

![SS 2020-10-09 at 19 56 25](https://user-images.githubusercontent.com/1001444/95575366-8ab69f00-0a69-11eb-8269-f4688201f3c9.png)

**Comment by shyr** [comment]
Great! Thank you for the wonderful extension. It's really useful for me.
