### ISSUE TITLE
How to add line breaks?

### ISSUE THREAD

**Issue by LeeteqXV** [zaki-yama/copy-title-and-url-as-markdown#6]
I tried the following, which does not produce a line break:
[${title}]\n(${url})

Is it possible to make the URL start on its own line?
Also want to add a line break to the end, AFTER the URL.

**Comment by LeeteqXV** [comment]
Example: I am looking for the possibility to do something like this: 
[${title}]\n(${url})\n

**Comment by LeeteqXV** [comment]
And this: 
[${title}]\n(${url})\n\n
(so that with two line breaks at the end, one may continue copying/pasting new urls with will then automatically get a blank line between each pair, so it is convenient to work fast without the need to move the hand between keyboard and mouse each time.

**Comment by zaki-yama** [comment]
@LeeteqXV 
I'm terribly sorry for late response.
I updated the extension, now you can add line breaks in option page.
Please try it.
